### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by samvekemans** [cmda-bt/fe-course-21-22#13]
# Enhancement

## Name
Sam Vekemans

## Class
tech-4

## Repo link
https://github.com/samvekemans/project-tech

## Summary
Ik heb mijn kennis over javascript weer omhoog gehaald, nou ben ik tijdens mijn stage al veel bezig geweest met javascript en heb ik er al enig verstand van wat mij erg gaat helpen. Ook heb ik nagedacht over mijn progressive enhancement, ik heb hierbij bedacht om iets met de locatie van de gebruiker te gaan doen. 

## Resources used
Github pagina van front-end
https://www.smashingmagazine.com/2009/04/progressive-enhancement-what-it-is-and-how-to-use-it/

## Any thoughts?
Ik vond het leuk om te bekijken hoe websites eruit zien zonder javascript.

**Comment by Chazzers** [comment]
Hi, gaaf dat je misschien iets wilt doen met de locatie van een gebruiker. Zelf heb ik hier nog nooit mee gewerkt, dus ik kan moeilijk oordelen of dit lastig is of niet. Probeer even met je frontend docent hier over te sparren. Succes!
