### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by samvekemans** [cmda-bt/fe-course-21-22#18]
# DOM Manipulation

## Name
Sam Vekemans

## Class
Tech-4

## Repo link
https://github.com/samvekemans/project-tech

## Summary
Ik heb een klein stukje javascript geschreven om een profiel foto die via een input word toegevoegd te laten zien. Verder heb ik mijn kennis over API's weer een beetje opgefrist. 

## Resources used
https://github.com/public-apis/public-apis

## Any thoughts?
Ik vond het leuk om weer javascript te schrijven en de dingen die ik op me stage geleerd heb te gebruiken.

**Comment by deannabosschert** [comment]
# Feedback
Hi Sam,

Goed bezig!
Ik zie dat je inmiddels ook al je connectie met MongoDB erin hebt zitten en gebruikersdata in je database opslaat, je bent lekker op weg.

Je wiki is nog wel tamelijk leeg, vergeet je niet om ook je documentatie bij te houden? Zeker je onderzoek naar API's kun je het beste gelijk daar documenteren.

---     


Ga zo door en geef een gil wanneer je vragen hebt, succes!


![gif of a cat giving a person a high five, with the text 'YEAH!' in meme font displayed underneath it](https://c.tenor.com/_BaYDIbn3dgAAAAC/yay-up.gif)
